FROM postgres

USER postgres
WORKDIR /app

COPY jvm/src/main/SQL/create.sql /docker-entrypoint-initdb.d/1_create.sql
COPY jvm/src/main/SQL/init.sql /docker-entrypoint-initdb.d/2_insert-test-data.sql
COPY jvm/src/main/SQL/localidades.csv /docker-entrypoint-initdb.d/localidades.csv

COPY --chown=postgres:postgres ./tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432